package FirstOrderLogic.actions;

/*Generated by MPS */

import jetbrains.mps.actions.descriptor.BaseActionAspectDescriptor;
import jetbrains.mps.openapi.actions.descriptor.ActionAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;

public class ActionAspectDescriptorImpl extends BaseActionAspectDescriptor implements ActionAspectDescriptor {
  private static final String LANGUAGE_FQ_NAME = "FirstOrderLogic";

  @Override
  public Collection<NodeFactory> getFactories(SAbstractConcept concept) {
    if (LANGUAGE_FQ_NAME.equals(concept.getLanguage().getQualifiedName())) {
      switch (concept.getName()) {
        case "PredicateAtomicStatement":
          return Collections.<NodeFactory>singletonList(new AtomicStatementConverters.NodeFactory_5925154266062172516());
        case "TermEqualsAtomicStatement":
          return Collections.<NodeFactory>singletonList(new AtomicStatementConverters.NodeFactory_5925154266062179071());
        default:
      }
    }
    return Collections.<NodeFactory>emptyList();
  }

}
