package FirstOrderLogic.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AAtomicStatement = 0;
  public static final int ADeclarable = 1;
  public static final int AOperatorStatement = 2;
  public static final int AQuantifiedStatement = 3;
  public static final int AStatement = 4;
  public static final int ATermComponent = 5;
  public static final int AllQuantifiedStatement = 6;
  public static final int Comment = 7;
  public static final int Constant = 8;
  public static final int ConstantListEntry = 9;
  public static final int ConstantReference = 10;
  public static final int EmptyAtomicStatement = 11;
  public static final int EmptyLine = 12;
  public static final int EmptyStatement = 13;
  public static final int ExistsQuantifiedStatement = 14;
  public static final int Function = 15;
  public static final int FunctionListEntry = 16;
  public static final int FunctionReference = 17;
  public static final int ICommonPattern = 18;
  public static final int IDeclarableReference = 19;
  public static final int ISheetEntry = 20;
  public static final int KnowledgeBaseEntry = 21;
  public static final int NegatedStatement = 22;
  public static final int ParenthesesStatement = 23;
  public static final int Predicate = 24;
  public static final int PredicateAtomicStatement = 25;
  public static final int PredicateListEntry = 26;
  public static final int PredicateReference = 27;
  public static final int Sheet = 28;
  public static final int Term = 29;
  public static final int TermEqualsAtomicStatement = 30;
  public static final int Variable = 31;
  public static final int VariableReference = 32;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x5d8a3d04c5e547e4L, 0x806d03da42a8c2cbL);
    builder.put(0x41354ec0cded1c6cL, AAtomicStatement);
    builder.put(0x5c35fb00b2182cL, ADeclarable);
    builder.put(0x13ba598d20c7b087L, AOperatorStatement);
    builder.put(0x13ba598d20c998f8L, AQuantifiedStatement);
    builder.put(0x13ba598d20c7b07fL, AStatement);
    builder.put(0x5c35fb00b9b603L, ATermComponent);
    builder.put(0x13ba598d20c99906L, AllQuantifiedStatement);
    builder.put(0x42ef795a3ccd6007L, Comment);
    builder.put(0x5c35fb00abee10L, Constant);
    builder.put(0x5c35fb00ac8357L, ConstantListEntry);
    builder.put(0x5c35fb00b9b606L, ConstantReference);
    builder.put(0x523a606984011431L, EmptyAtomicStatement);
    builder.put(0x42ef795a3cc8ef2aL, EmptyLine);
    builder.put(0x13ba598d20c830f7L, EmptyStatement);
    builder.put(0x1bf6498e1734c76cL, ExistsQuantifiedStatement);
    builder.put(0x5c35fb00b217e4L, Function);
    builder.put(0x5c35fb00b32488L, FunctionListEntry);
    builder.put(0x5c35fb00b2183aL, FunctionReference);
    builder.put(0x42ef795a3ccd6001L, ICommonPattern);
    builder.put(0x523a606984019bbbL, IDeclarableReference);
    builder.put(0x5c35fb00ac8463L, ISheetEntry);
    builder.put(0x636efe58094cc959L, KnowledgeBaseEntry);
    builder.put(0x36e551eaf2c8dae6L, NegatedStatement);
    builder.put(0x36e551eaf2ccfec9L, ParenthesesStatement);
    builder.put(0x41354ec0cdeac250L, Predicate);
    builder.put(0x41354ec0cdece64dL, PredicateAtomicStatement);
    builder.put(0x41354ec0cdeaf521L, PredicateListEntry);
    builder.put(0x523a606984019bbaL, PredicateReference);
    builder.put(0x5c35fb00ac843eL, Sheet);
    builder.put(0x5c35fb00b21835L, Term);
    builder.put(0x636efe58094ad65bL, TermEqualsAtomicStatement);
    builder.put(0x5c35fb00b08382L, Variable);
    builder.put(0x13ba598d20cb7c36L, VariableReference);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
